version: '3.3'
services:
  mysql:
    image: mysql:8.0
    container_name: securecapita
    environment:
      - MYSQL_DATABASE=securecapita
      - MYSQL_USER=user
      - MYSQL_PASSWORD=changemeinprod
      - MYSQL_ROOT_PASSWORD=changemeinprod
    ports:
      - "3306:3306"