version: '3.3'
services:
  mysql:
    image: mysql:latest
    container_name: securecapita
    environment:
      - MYSQL_DATABASE=securecapita
      - MYSQL_USER=root
      - MYSQL_PASSWORD=changemeinprod
    ports:
      - "3306:3306"